import NavBar from '@/components/nav/navbar';
import Footer from '@/components/nav/footer';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar></NavBar>
      <main>
        <div></div>
      </main>
      <Footer></Footer>
    </>
  );
}
